language: go

#版本
go:
  - 1.9
#环境变量
env:
  - GO19VENDOREXPERIMENT=1
#  - "PATH=/home/travis/gopath/bin:$PATH"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/vaniot-s/video
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/vaniot-s/video/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/vaniot-s/video
  - cd $HOME/gopath/src/github.com/vaniot-s/video
sudo: required

#安装
before_install:
  - go get github.com/julienschmidt/httprouter
  - go get github.com/go-sql-driver/mysql
install:
  - echo "install"

script:
#  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...


after_success:
  - echo "success"