language: go

#版本
go:
  - 1.9
#环境变量
env:
#  - "PATH=/home/travis/gopath/bin:$PATH"
#权限
sudo: required

#安装
before_install:
  - go get github.com/julienschmidt/httprouter
  - go get github.com/go-sql-driver/mysql
install:
  - echo "install"

script:
  - go test ./..


after_success:
  - echo "success"